version: "3.9"
services:
    dksybase:
        image: "ifnazar/sybase_15_7"
        ports: 
            - "5000:5000"
        command: ["bash",  "/sybase/start"]
        volumes:
            - ~/.dksybase:/opt/sybase/external_data
    test:
        build: .
        depends_on: 
            - "dksybase"
        volumes:
            - ~/extract:/usr/src/app/extract